In [1]:
import numpy as np
import pandas as pd


In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/Jash1005/MACHINE-LEARNING/refs/heads/main/Missing%20Values/50_startup.csv')
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [12]:
new_df = df[['Administration','Marketing Spend','R&D Spend','Profit']]/1000
np.random.seed(9)
new_df = new_df.sample(5)

In [13]:
new_df = new_df.iloc[:,0:-1]
new_df

Administration  Marketing Spend  R&D Spend
21       153.77343        299.73729   78.38947
37        51.28314        197.02942   44.06995
2        101.14555        407.93454  153.44151
14       156.54742        256.51292  119.94324
44       154.80614         28.33472   22.17774

In [25]:
#introducing some null values

new_df.iloc[1,0] = np.nan
new_df.iloc[3,1] = np.nan
new_df.iloc[-1,-1] = np.nan
new_df.head()

Administration  Marketing Spend  R&D Spend
21       153.77343        299.73729   78.38947
37             NaN        197.02942   44.06995
2        101.14555        407.93454  153.44151
14       156.54742              NaN  119.94324
44       154.80614         28.33472        NaN

In [43]:
from sklearn.impute import SimpleImputer

# Assuming new_df is already defined and contains the columns with NaNs
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit and transform the selected columns
imputed_data = imp_mean.fit_transform(new_df[['Administration', 'Marketing Spend', 'R&D Spend']])

# Assign the imputed values back to the DataFrame
new_df[['Administration', 'Marketing Spend', 'R&D Spend']] = imputed_data


In [45]:
new_df

df0 = new_df.copy()

In [47]:
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

Administration  Marketing Spend   R&D Spend
21       153.77343       299.737290   78.389470
37             NaN       197.029420   44.069950
2        101.14555       407.934540  153.441510
14       156.54742       233.258992  119.943240
44       154.80614        28.334720   98.961043

In [48]:
X = df1.iloc[[0,2,3,4],1:3]
X

Marketing Spend   R&D Spend
21       299.737290   78.389470
2        407.934540  153.441510
14       233.258992  119.943240
44        28.334720   98.961043

In [49]:
y = df1.iloc[[0,2,3,4],0]
y

21    153.77343
2     101.14555
14    156.54742
44    154.80614
Name: Administration, dtype: float64

In [50]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([181.3151674])

In [54]:
df1.iloc[1,0] = 181.315

df1

Administration  Marketing Spend   R&D Spend
21       153.77343       299.737290   78.389470
37       181.31500       197.029420   44.069950
2        101.14555       407.934540  153.441510
14       156.54742       233.258992  119.943240
44       154.80614        28.334720   98.961043

In [55]:
# second col

df1.iloc[3,1] = np.nan

df1

Administration  Marketing Spend   R&D Spend
21       153.77343        299.73729   78.389470
37       181.31500        197.02942   44.069950
2        101.14555        407.93454  153.441510
14       156.54742              NaN  119.943240
44       154.80614         28.33472   98.961043

In [58]:
X = df1.iloc[[0,1,2,4],[0,-1]]
Y = df1.iloc[[0,1,2,4],1]

lr.fit(X,Y)
lr.predict(df1.iloc[3,[0,-1]].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-266.18974175])

In [60]:
df1.iloc[3,1] = -266.18

In [62]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

Administration  Marketing Spend  R&D Spend
21       153.77343        299.73729   78.38947
37       181.31500        197.02942   44.06995
2        101.14555        407.93454  153.44151
14       156.54742       -266.18000  119.94324
44       154.80614         28.33472        NaN

In [64]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

y = df1.iloc[0:4,-1]
y

21     78.38947
37     44.06995
2     153.44151
14    119.94324
Name: R&D Spend, dtype: float64

In [65]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([99.07334134])

In [66]:
df1.iloc[4,-1] = 99.07

In [67]:
df1

Administration  Marketing Spend  R&D Spend
21       153.77343        299.73729   78.38947
37       181.31500        197.02942   44.06995
2        101.14555        407.93454  153.44151
14       156.54742       -266.18000  119.94324
44       154.80614         28.33472   99.07000

In [68]:
df0 - df1

Administration  Marketing Spend  R&D Spend
21        0.000000         0.000000   0.000000
37      -39.746865         0.000000   0.000000
2         0.000000         0.000000   0.000000
14        0.000000       499.438992   0.000000
44        0.000000         0.000000  -0.108957